---
- name: install lamp server on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: install apache surver
      ansible.buildin.yam:
        name: httpd
        state: present 
    - name: enable and start apache
      ansible.builtin.systemd:
        name: httpd
        enabled: yes
        state: started    
    - name: install apache surver
      ansible.buildin.yam:
        name: php
        state: present
    - name: copy info.php 
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
    - name: restart apache
      ansible.builtin.systemd:
        name: httpd
        state: restart
        