---
- name: install lsmp server on ubuntu
  hosts: all
  become: yes
  tesks:
   - name: update packages and install apcahi
     ansible.builtin.apt:
       name: apache2
       update_cache: yes
       state: present
   - name: install php packages
     ansible.builtin.apt:
       name: 
         - php
         - libapache2-mod-php
         - php-mysql
       state: present
   - name: copy php to other node 
     ansible.builtin.copy:
       src: info.php
       dest: /var/www/html/info.php
   - name: restart apache2
     ansible.builtin.systemd:
       name: apache2
       state: restarted

